### ISSUE TITLE
Loading 'custom.el'

### ISSUE THREAD

**Issue by s-hong-s** [m-parashar/emax64#10]
The script for loading 'custom.el' is located in the middle of 'emax.el'.
So, a script, which is written in 'custom.el', may be ignored by 'emax.el'.
I think it would be better if 'custom.el' and 'secure.el' are loaded at the end of 'emax.el'
Thanks.

**Comment by m-parashar** [comment]
At present the emax.org/el are highly stripped-down versions of my personal configuration. I'll make the necessary changes, and if time permits - add things to it too, in the next release. Thank you for your feedback.
