### ISSUE TITLE
feature request: Add support for emacs pdumper

### ISSUE THREAD

**Issue by et2010** [m-parashar/emax64#11]
Hi, Manish

Thank you for building emax64. It works perfectly. However, one thing that bothers me is the slow loading speed on Windows since I installed lots of packages. One way to mitigate this problem is to use pdumper version of emacs. I tried to compile it myself, but couldn't figure out how to configure imagemagick to work properly. I think it would be great if emax64 could support pdumper. Please consider building a pdumper version of emax64. Thanks!

**Comment by m-parashar** [comment]
Hello et2010,

I have just released an emax64 version of the emacs-pdumper branch. Get it here: https://github.com/m-parashar/emax64/releases/tag/pdumper-20180619

See if everything works as it should.

**Comment by et2010** [comment]
Thanks! That's great!

**Comment by ejemba** [comment]
@et2010 does it improve your loading speed on Windows ?

**Comment by et2010** [comment]
Yes, the loading time is improved greatly. with 360+ packages, from 2+ minutes to within 3 seconds.
