### ISSUE TITLE
Error after update use-package

### ISSUE THREAD

**Issue by poulpoulsen** [m-parashar/emax64#12]
hello,
i just installed your new version and it starts ok.
But after update packages there is an error with use-package.
I compare this with my oroginal emacs and there was no error with this package.
Any clues?
Here is the error message:
Leaving directory ‘c:/Users/Held/emax/elpa/use-package-20180613.2219’

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-bind-key.el at Sat Jun 23 09:23:22 2018
Entering directory ‘c:/Users/Held/emax/elpa/use-package-20180613.2219/’
use-package-bind-key.el:39:1:Error: Loading file c:/Users/Held/emax/elpa/bind-key-20180512.2130/bind-key.elc failed to provide feature ‘bind-key’

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-core.el at Sat Jun 23 09:23:22 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-delight.el at Sat Jun 23 09:23:23 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-diminish.el at Sat Jun 23 09:23:23 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-ensure.el at Sat Jun 23 09:23:23 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-jump.el at Sat Jun 23 09:23:23 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package-lint.el at Sat Jun 23 09:23:23 2018

Compiling file c:/Users/Held/emax/elpa/use-package-20180613.2219/use-package.el at Sat Jun 23 09:23:23 2018
use-package.el:44:1:Error: Loading file c:/Users/Held/emax/elpa/bind-key-20180512.2130/bind-key.elc failed to provide feature ‘bind-key’

Compiling no file at Sat Jun 23 09:23:26 2018

Regards
Poul

**Comment by poulpoulsen** [comment]
FYI:
After i uninstall manually the old use-package and bind-key and install the new use-package the error is gone. Strange!

Regards
Poul

**Comment by m-parashar** [comment]
I'll look into it and update the emax.7z archive. Thanks for reporting.
