### ISSUE TITLE
Correct way to tramp?

### ISSUE THREAD

**Issue by jingxuanlim** [m-parashar/emax64#13]
Hey m-parashar, love your emax64 built for supporting Imagemagick. I've been trying for the past 3 hours to properly use tramp, with no success... Would you mind shedding some light?

SSH-ing on msys2 initially raised some error about creating `\home\<user>\.ssh` which I was able to fix by (1) adding the following line to `etc/fstab`

```
C:/home /home ntfs binary,noacl,auto 1 1
```
and (2) changing the following line in `/etc/nssswitch.conf` to

```
db_home: windows
```

Tramp still hangs after making those changes (i.e. no problem SSH-ing via msys2 shell).

I then setup `ssh-agent` thinking that it is a password prompt problem so now I can SSH via msys2 shell without a prompt for password.

Tramp still hangs...

I've been trying and hoping for tramp for almost 2 years now... Any help appreciated! Thanks!

**Comment by cireu** [comment]
Can you read Chinese?
Here is an article may help you which is totally written in Chinese.

https://chriszheng.science/2018/01/28/Tramp-config-for-MS-Windows-to-UNIX/
