### ISSUE TITLE
imagemagick: No thumbs and could not resize

### ISSUE THREAD

**Issue by vovav80** [m-parashar/emax64#15]
Hi,
I can view images in dired. The new buffer uses imagemagick and resized images to fit the window.

However, image-dired returns an error "thumb could not be created for ...*png".
Trying to view images from helm-find-files does not show images either, saying "could not resize"

I am on Windows 8.1

Any ideas?

**Comment by m-parashar** [comment]
Thanks for reporting. I'll look into it and release a new build soon enough.

**Comment by vovav80** [comment]
When the path to emacs executables moved to the beginning in the PATH environmental variable, everything started to work absolutely fine.

**Comment by m-parashar** [comment]
Glad it was solved.
