### ISSUE TITLE
Can't see PDF-TOOLS menu 

### ISSUE THREAD

**Issue by Ypot** [m-parashar/emax64#16]
I uncompressed and got the emax64pd folder. Moved it to C:\. Run installation.
But I can't see the menu where PDF-TOOLS appear, like in the Readme.
I get this instead
![img_20180816_091857044](https://user-images.githubusercontent.com/30699014/44194616-cfb74300-a136-11e8-97d1-804ac8cd91b8.jpg)
Thanks for your work

**Comment by m-parashar** [comment]
You need to decompress this file (https://github.com/m-parashar/emax64/releases/download/20180529/emax.7z) into your HOME folder (C:\Users\USERNAME\AppData\Roaming). If you have your own .emacs file and the whole shebang, just copy the elpa\PDF-TOOLS folder to your config and load it.
