### ISSUE TITLE
Step-by-step instructions to build Emacs for Windows 64

### ISSUE THREAD

**Issue by colin4124** [m-parashar/emax64#2]
I have followed this https://gist.github.com/nauhygon/f3b44f51b34e89bc54f8 before, but I have some wrong with xpm support, would you share your compiling steps for us?

**Comment by m-parashar** [comment]
Gladly.

1. Install MSYS2
2. pacman -Syu
3. pacman -Su
4.
pacman -S base-devel mingw-w64-x86_64-toolchain \
mingw-w64-x86_64-xpm-nox mingw-w64-x86_64-libtiff \
mingw-w64-x86_64-giflib mingw-w64-x86_64-jbigkit \
mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo \
mingw-w64-x86_64-librsvg mingw-w64-x86_64-libxml2 \
mingw-w64-x86_64-gnutls mingw-w64-x86_64-zlib \
mingw-w64-x86_64-imagemagick mingw-w64-x86_64-poppler \
mingw-w64-x86_64-brotli

5. pacman -S git
6. git clone git://git.savannah.gnu.org/emacs.git
7. cd emacs
8. git config core.autocrlf false

./autogen.sh
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig CFLAGS=" -O2 -g3" ./configure --without-compress-install --without-dbus --with-modules
make
make info --no-print-directory
make install-strip prefix=/c/emaxw64

cp /mingw64/bin/{libxpm.dll,xpm4.dll,libXpm-nox4.dll} /c/emax64/bin
cp /mingw64/bin/{libjpeg*.dll,libtiff*.dll,libpng16*.dll} /c/emax64/bin
cp /mingw64/bin/{liblcms2*.dll,zlib*.dll,libz*.dll,libtiffxx-*.dll} /c/emax64/bin
cp /mingw64/bin/{libxml2*.dll,libgobject-2*.dll,libgnutls*.dll} /c/emax64/bin
cp /mingw64/bin/{libMagickWand-7*.dll,libMagickCore-7*.dll} /c/emax64/bin
cp /mingw64/bin/{libgdk_pixbuf-2*.dll,librsvg-2*.dll,libgif*.dll} /c/emax64/bin
cp /mingw64/bin/{libidn*.dll,libpcre*.dll,libunistring*.dll} /c/emax64/bin
cp /mingw64/bin/{libgmp-*.dll,libhogweed-*.dll,libnettle-*.dll} /c/emax64/bin
cp /mingw64/bin/{libp11-kit-*.dll,libtasn1-*.dll,libstdc*.dll} /c/emax64/bin
cp /mingw64/bin/{libwinpthread-*.dll,libjbig-*.dll,libssh2-*.dll} /c/emax64/bin
cp /mingw64/bin/{libgomp-*.dll,libgcc_s_seh-*.dll,libffi-*.dll} /c/emax64/bin
cp /mingw64/bin/{libintl-*.dll,libiconv-*.dll,libgio-*.dll} /c/emax64/bin
cp /mingw64/bin/{libgmodule-*.dll,libgraphite*.dll,libglib-2*.dll} /c/emax64/bin
cp /mingw64/bin/{libcairo-*.dll,libcroco-*.dll,libpango-*.dll} /c/emax64/bin
cp /mingw64/bin/{libpangocairo-*.dll,libfontconfig-*.dll} /c/emax64/bin
cp /mingw64/bin/{libfreetype-*.dll,libpixman-*.dll,libexpat-*.dll} /c/emax64/bin
cp /mingw64/bin/{libpangoft*.dll,libpangowin32-*.dll,liblzma-*.dll} /c/emax64/bin
cp /mingw64/bin/{libfftw3-*.dll,libraqm-*.dll,libltdl-*.dll} /c/emax64/bin
cp /mingw64/bin/{libbz2-*.dll,libfribidi-*.dll,liblqr*.dll} /c/emax64/bin
cp /mingw64/bin/{libdjvulibre-*.dll,libjasper-*.dll,libopenjp*.dll} /c/emax64/bin
cp /mingw64/bin/{smime3*.dll,ssleay32*.dll,libharfbuzz-*.dll} /c/emax64/bin
cp /mingw64/bin/{libeay32*.dll,nss3*.dll,nssutil3*.dll} /c/emax64/bin
cp /mingw64/bin/{libnspr*.dll,libnghttp2-*.dll,libpixman-1*.dll} /c/emax64/bin
cp /mingw64/bin/{libplc4*.dll,libplds4*.dll,libcurl-4*.dll} /c/emax64/bin
cp /mingw64/bin/{libpoppler-7*.dll,libpoppler-glib-*.dll,libbrotli*.dll} /c/emax64/bin

9. make clean

**Comment by colin4124** [comment]
Thanks Very Much!
