### ISSUE TITLE
C-h C-a (about-emacs) returns error

### ISSUE THREAD

**Issue by m-parashar** [m-parashar/emax64#21]
C-h C-a (about Emacs) causes the following issue which wasn't present in previous releases:

`Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  use-fancy-splash-screens-p()
  about-emacs()
  funcall-interactively(about-emacs)
  call-interactively(about-emacs nil nil)
  command-execute(about-emacs)`

This is likely due to the ImageMagick7 patch. I haven't had time to look into it. If you encounter more such errors, please report.

**Comment by jtwil** [comment]
Seems to be a problem with the SVG support. I get the following error when opening a SVG file:
`ImageMagick error: unable to load module 'C:/Users/Jtw/Emacs/emacs/lib/ImageMagick-7.0.8/modules-Q16HDRI/coders\svg.la': The specified module could not be found. @ error/module.c/OpenModule/1291`

**Comment by m-parashar** [comment]
I built against ImageMagick 6.9 (unpatched) and got the same error. `ImageMagick error: unable to load module `C:/emax64/lib/ImageMagick-6.9.3/modules-Q16HDRI/coders\svg.la': The specified procedure could not be found. @ error/module.c/OpenModule/1305`

It's definitely not the patch or even ImageMagick 7 as the modules are there in both builds. I may have to find some time to look into it.

**Comment by jtwil** [comment]
Any progress on this?

**Comment by m-parashar** [comment]
Haven't had the time to look into it, unfortunately. I'll find time this weekend.

**Comment by m-parashar** [comment]
Uploaded a new release. Fixed.
