### ISSUE TITLE
doom-modeline-height doesn't take effect in emax64

### ISSUE THREAD

**Issue by zijianyue** [m-parashar/emax64#22]
doom mode-line height seems not right

![image](https://user-images.githubusercontent.com/6119928/56403755-7a1ed180-6295-11e9-9e43-da78e17c70f7.png)

Using emax64 26.2 (a version build for windows)
https://github.com/m-parashar/emax64

The official version emacs 26.2
![image](https://user-images.githubusercontent.com/6119928/56403763-80ad4900-6295-11e9-9910-5c6273c41762.png)

**Comment by seagle0128** [comment]
See https://github.com/seagle0128/doom-modeline/issues/156#issuecomment-484779275

> I believe libXmp-noX4.dll is missing in emax64 package. Maybe more other libs are missing as well. Copy dll libs and the issue disappears.

In my tests, even the *about* buffer was unable to be opened.

**Comment by zijianyue** [comment]
libXpm-nox4.dll

**Comment by seagle0128** [comment]
Right! typo. You need to check other libs.

**Comment by m-parashar** [comment]
The DLL was indeed missed by the automated build process. It will be included in the next release.
