### ISSUE TITLE
Any plans to get this on CI/CD (AppVeyor)?

### ISSUE THREAD

**Issue by xeijin** [m-parashar/emax64#24]
It's free for open source projects & provides images for a variety of Windows distributions (7 - 10) and could mean we get newer releases without too much effort on your part?

**Comment by xeijin** [comment]
@m-parashar ?

**Comment by m-parashar** [comment]
https://github.com/m-parashar/emax64/releases/tag/20191225

I will definitely look into it. Parts of the process still require some manual effort, like patching new code and getting around bugs or failures due to unreachable servers, but most of it can certainly be automated.
