### ISSUE TITLE
pdf-tools wants to compile

### ISSUE THREAD

**Issue by vovav80** [m-parashar/emax64#26]
Hi. I am following your instructions. emax64 in in C:\, emax in Roaming. But I don't want to install msys2. Would pdf-tools work?
Every time I open emacs, it asks whether I have msys2 and tries to compile with error "Building the PDF Tools server failed"
Any suggestions?
Thank you

**Comment by xx299x** [comment]
```
  (require 'pdf-tools-extension)
  (setq pdf-info-epdfinfo-program '"c:/users/xx299/.spacemacs.d/pdf-tools-20190413.2018/epdfinfo.exe")
```
You can manual set the pdf-info-epdfinfo-program.

**Comment by vovav80** [comment]
Thank you
(setq pdf-info-epdfinfo-program ...
worked.
