### ISSUE TITLE
Ignores an already set HOME environment variable

### ISSUE THREAD

**Issue by peschkaj** [m-parashar/emax64#29]
I've set `HOME` to my actual user folder: `C:\Users\<username>`. emacx64 ignores this and uses `%APPDATA%` as if it were the `HOME` environment variable. 

If `HOME` is set, I would expect programs to respect that environment variable.

**Comment by m-parashar** [comment]
Can you reproduce this with the official binary distribution?

I have just uploaded an unpatched 26.3, which plays nice with pdf-tools but lacks im7 support. Also included is a snapshot build of emacs-master without the patches.

**Comment by peschkaj** [comment]
This was a configuration issue on my end. I appear to have unset `HOME`. 

I verified that both the build from 5 days ago and the snapshot build will respect the system set `HOME` environment variable.
