### ISSUE TITLE
Error with pdf-tools on each load

### ISSUE THREAD

**Issue by billdenney** [m-parashar/emax64#31]
I have what I think is the same issue as #26.  Is there a way to disable pdf-tools from loading?

I don't need pdf-tools, but I'd prefer not to get the compilation error every time.  Is it possible to check for a valid C compiler before attempting the installation or somehow remove the need for the C compiler?

My fix was simply to remove pdf-tools from the `%appdata%\emax\elpa` directory and then comment out the `;;(pdf-tools-install :no-query)` line in `%appdata%\emax\elpa\emax.el`.

**Comment by m-parashar** [comment]
Yes, pdf-tools can simply be removed/uninstalled.
