### ISSUE TITLE
Version GNU Emacs 28.0.50  keep poping "Buffer recentf<n> modified; kill anyway?"

### ISSUE THREAD

**Issue by onriv** [m-parashar/emax64#32]
with release: https://github.com/m-parashar/emax64/releases/tag/20191229

![image](https://user-images.githubusercontent.com/1629055/79420308-44691180-7feb-11ea-9fbb-a99085669ef7.png)

no matter y or n, it open a buffer:

![image](https://user-images.githubusercontent.com/1629055/79420333-51860080-7feb-11ea-94cd-7f9d4fded34e.png)

**Comment by m-parashar** [comment]
Alpha release. Please file these bugs with the official Emacs team. I encourage you to use the latest release build (27.1), see if you can replicate it.
