### ISSUE TITLE
feature request: feature/native-comp branch

### ISSUE THREAD

**Issue by jguenther** [m-parashar/emax64#34]
the `feature/native-comp` branch (which looks like it might make it to emacs 28 release, and is up to date with master) links against `libgccjit` to allow emacs to compile (at runtime) emacs lisp to native machine code, which can be a pretty big speed boost. 

emacs on windows is always the slowest for me so I'm curious if this branch would make a difference on w64 performance, but I have no idea how to do this on windows

I think if you install the libgccjit lib (gcc compiled with `--enable-language jit` IIRC), --with-nativecomp is the configure option for emacs to enable this

if you have any pointers on how to get that libgccjit on windows and include it in the build I'd be willing to try to help if I can

**Comment by m-parashar** [comment]
I'll certainly look into it and reopen/update the post when I do.
