### ISSUE TITLE
Reproduce build?

### ISSUE THREAD

**Issue by vsalvino** [m-parashar/emax64#36]
Hello - I am in the process of creating a repo which automatically builds emacs for Windows nightly from the latest sources (via GitHub Actions - see https://github.com/vsalvino/emacs-windows/blob/main/.github/workflows/build.yml)

The last step of the process I have not figured out, and is not documented, is how to correctly bundle the required DLLs with the installed files. It seems that you are doing this, but have not documented how.

Do you have any wisdom for how to hunt down these necessary dependencies? Is it a manual effort to copy them from mingw? Or can it be scripted somehow?

**Comment by phillord** [comment]
There is code for this in the Emacs source, specifically `admin/nt/dist-build/build-deps-zips.sh`. It's changed quite a lot between Emacs-27 and Emacs-28, so feel free to compare and contrast.

Apologies for hijacking this issue, nothing to do with this repo really.

**Comment by vsalvino** [comment]
Thanks @phillord ! I could not find this documented anywhere. Tribal knowledge I guess. I was only asking here since it seemed this repo was already doing it.
