### ISSUE TITLE
emacs error after update with emax

### ISSUE THREAD

**Issue by poulpoulsen** [m-parashar/emax64#4]
hello,
after automatically updating the neccessary packages from elpa, org after the first start i got the following error message (with emacs --debug-init).
Any clues?

Regards
Poul

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  load-file(nil)
  org-babel-load-file("c:/Users/Held/emax/emax.org")
  (let ((gc-cons-threshold most-positive-fixnum)) (require 'package) (setq-default load-prefer-newer t package-enable-at-startup nil) (if (member '("melpa" . "http://melpa.org/packages/") package-archives) package-archives (setq package-archives (append package-archives (list '("melpa" . "http://melpa.org/packages/"))))) (if (member '("org" . "http://orgmode.org/elpa/") package-archives) package-archives (setq package-archives (append package-archives (list '("org" . "http://orgmode.org/elpa/"))))) (setq package-user-dir "~/emax/elpa") (package-initialize) (if (and (package-installed-p 'delight) (package-installed-p 'use-package)) nil (package-refresh-contents) (package-install 'delight t) (package-install 'use-package t)) (setq-default use-package-always-defer t use-package-always-ensure t) (use-package org :ensure org-plus-contrib) (defvar emax-root (concat (expand-file-name "~") "/emax")) (defvar emax-bin (concat emax-root "/bin")) (defvar emax-bin64 (concat emax-root "/bin64")) (defvar emax-mingw64 (concat emax-root "/mingw64/bin")) (defvar emax-lisp (concat emax-root "/lisp")) (setq exec-path (cons emax-bin exec-path)) (setenv "PATH" (concat emax-bin ";" (getenv "PATH"))) (setq exec-path (cons emax-bin64 exec-path)) (setenv "PATH" (concat emax-bin64 ";" (getenv "PATH"))) (setq exec-path (cons emax-mingw64 exec-path)) (setenv "PATH" (concat emax-mingw64 ";" (getenv "PATH"))) (let ((--dolist-tail-- '("~/emax/" "~/emax/bin/" "~/emax/bin64/" "~/emax/mingw64/bin/" "~/emax/lisp/" "~/emax/elpa/")) dir) (while --dolist-tail-- (setq dir (car --dolist-tail--)) (add-to-list 'load-path dir) (setq --dolist-tail-- (cdr --dolist-tail--)))) (set-language-environment 'utf-8) (setq locale-coding-system 'utf-8) (set-default-coding-systems 'utf-8) (set-terminal-coding-system 'utf-8) (prefer-coding-system 'utf-8) (org-babel-load-file (expand-file-name "~/emax/emax.org" user-emacs-directory)) (garbage-collect))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Held/.emacs" nil t)  ; Reading at buffer position 2557
  load-with-code-conversion("c:/Users/Held/.emacs" "c:/Users/Held/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1000c030d>)()
  command-line()
  normal-top-level()

**Comment by m-parashar** [comment]
Hi there,

Upgrade to the 20180303 release, Emacs and emax both. This new release has full debug info enabled for a complete stack trace. I have disabled garbage collection in emax.org as well. Have you installed any packages since? 'Cause I cannot reproduce the error.

**Comment by poulpoulsen** [comment]
hello,
thanks for the quick response.
I managed it to run with version 20180302.
Fault was a directory name.
The root directory should be emax.
Therefore i have to unpack emax.7z first to directory ~/emax.
Then unpack the binary into ~/emax.
Now it runs.
Two questions:
1. Is it neccessary to upgrade?
2. I want to customize (new packages, configuration options). Which file is the correct one? As far as understood, emacs and emacs.el are build from emacs.org and they are from you. Is ~/emacs.d/custom.el the right file?

Regards
Poul

**Comment by m-parashar** [comment]
Ah yes. The .emacs dotfile and emax directories should be in the user's Roaming directory (HOME). Yes, it's better to upgrade to 20180303 since it has full debug info enabled.

No, the ".emacs" file merely sets up PATH, loads org mode and dependencies and then loads emax\emax.org (which is compiled to emax.el). You should modify only the emax.org file as per your needs, and maybe .emacs if you wish to change those specific settings.

![emax](https://user-images.githubusercontent.com/1127541/36935662-6c6b2a52-1f20-11e8-946f-299aaac94cca.JPG)
![emax2](https://user-images.githubusercontent.com/1127541/36935681-ad8ea144-1f20-11e8-8df9-5be2cfb31dff.JPG)

**Comment by poulpoulsen** [comment]
oh i see.
Will do that and make my modifications inside emax.org.
Thanks

**Comment by kirill-gerasimenko** [comment]
Hi,

Can you share your `.emacs` file?

**Comment by poulpoulsen** [comment]
Hello,
i think you mean my generated emacs file out of emax.org?
But i will send you both.

PS: I asked this problem on reddit, but up to now, there is no
solution.
Some suggested to install smex or ivy or ido and so on.
I did and tried that. All packages work as expected, but not
inside m-x customize-group.
There is no pop-up or opening a file-browser if i start to press
~ or any other path. I could put in what i want. Very strange...
And the TAB also doesn't work as completion-starter.
Don' t know why...

Regards
Poul
