### ISSUE TITLE
no gnutls; eww could not load https

### ISSUE THREAD

**Issue by poulpoulsen** [m-parashar/emax64#6]
hello,
is it possible, that emax is packaged without gnutls activated?
eww could not load https sites. I read, that this could be the problem.

(gnutls-available-p) echoes no a true

Regards
Poul

**Comment by m-parashar** [comment]
Issue confirmed. emax is packaged with all the dependencies and them some. Looks like a problem with the 26.0.91 prerelease code, because this wasn't a problem with 26.0.90 (20171130) release.

I'll look into it and draft a new release soon.

**Comment by m-parashar** [comment]
I have uploaded a new release: 20180307, along with refreshed emax.7z package.

I looked into the 20180303 build and the eww/gnutls only creeps up if you're behind a proxy. Both 20180303 and 20180307 releases work well if there's no proxy to deal with. Look here: https://www.reddit.com/r/emacs/comments/7u51t4/eww_not_working_for_https_sites_in_emacs_26090/


<img width="710" alt="eww" src="https://user-images.githubusercontent.com/1127541/37098598-4a1c29f2-2244-11e8-925f-76e4c0c48406.PNG">
20180303 screenshot
