### ISSUE TITLE
Library source

### ISSUE THREAD

**Issue by phillord** [m-parashar/emax64#9]
I think that you need to include source for at least some of the libraries that you are distributing, such as gnutls, which are released under LGPL.

**Comment by m-parashar** [comment]
Thank you for bringing this to my attention. IANAL, but it seems providing links to source code is often enough, considering they are not modified. I have made suitable changes to the readme and release notes with links to sources as and when applicable. If I must host the sources on the same server as the binaries for redistribution, please do let me know and I will make them available.

Amendment to release notes:
````
Sources:
* GNU Emacs sources, patched as described above, are available as a separate src archive.
* All the other binaries included in the emax64 and emax archives are unmodified and distributed as is.
* Their sources can be downloaded from MSYS2/MinGW servers: http://repo.msys2.org/mingw/sources/
* BusyBox (Windows) sources can be obtained from here: https://frippery.org/files/busybox/

**Comment by phillord** [comment]
For GPL (or LGPL) code, you need the source I am afraid. Even unmodified binaries are covered.

The relevant bit of the license is this:

"Convey the object code by offering access from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge."

It's "through the same place" which gets you. The source needs to be on the same server. It's to prevent the situation where the binaries are available but the link to the source gets broken.

For other licenses, I don't know.

**Comment by m-parashar** [comment]
> It's "through the same place" which gets you. The source needs to be on the same server. It's to prevent the situation where the binaries are available but the link to the source gets broken.

Indeed.

> d) Convey the object code by offering access from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge. [...] If the place to copy the object code is a network server, the Corresponding Source may be on a different server (operated by you or a third party) that supports equivalent copying facilities, provided you maintain clear directions next to the object code saying where to find the Corresponding Source. Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.

For now, I have included the links and uploaded the sources for gnutls, and will upload any and all sources as necessary to comply with the license(s).
